FROM harbor.mellanox.com/swx-infra/x86_64/ubuntu20.04/builder@sha256:8316e5c4d22e9549b8472271abf9b74991897f10c6261c6cbc19686b5303452e
ARG _ARCH=x86_64

ARG _UID=6213
ARG _GID=101
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN
RUN mkdir -p $_HOME
RUN groupadd -f -g "$_GID" "$_LOGIN"
RUN useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "$_LOGIN"
RUN chown $_LOGIN $_HOME
RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER root
RUN yes|apt-get install -y sudo
ENV PATH="${PATH}:/hpc/local/bin:/hpc/local/oss/vma/"
ENV MODULEPATH="${MODULEPATH}:/hpc/local/etc/modulefiles"


RUN rm -rf /tmp/*
RUN cat /dev/null > ~/.bash_history
WORKDIR /tmp
